<?php
/**
 */

/**
 * Implements hook_form_alter().
 */
function shop_hosting_form_alter(&$form, &$form_state, $form_id){

}

function shop_hosting_hosting_tasks_alter(&$tasks) {
  
}
function shop_hosting_hosting_tasks() {
  $tasks = array(
    'server' => array(
      'delete' => array(
        'title' => t('Delete'), 
        'description' => t('Destroy this server.'), 
        'dialog' => TRUE,
      ),
    ),
  );
  return $tasks;
}

/**
 * Load attributes into our server node here.
 */
function shop_hosting_nodeapi_server_load(&$node){
  
  // Build attributes object
  $node->attributes = new stdClass;

  // Add server users: any users with role "administrator"
  $admin_role = variable_get('shop_server_admin_role', 'administrator');
  $admins = db_query('SELECT u.name, u.uid FROM users u LEFT JOIN users_roles ur on u.uid = ur.uid LEFT JOIN role r ON ur.rid = r.rid WHERE r.name = "%s" OR u.uid = 1 OR u.uid = %d', $admin_role, $node->uid);
  while ($account = db_fetch_object($admins)){
    $keys = sshkey_load_all_by_entity('user', $node->uid);
    $account->ssh_keys = array();
    foreach ($keys as $key){
      $ssh_keys[] = $key->value;
      $account->ssh_keys[] = $key->value;
    }
    // Adding each users authorized key.
    $node->attributes->devudo['users'][$account->name] = implode("\n", $account->ssh_keys);
  }
  
  // Authorized Keys to add to aegir user
  $node->attributes->aegir['authorized_keys'] = implode("\n", $ssh_keys);
  
  // Add this servers public key to devudo user.
  // To set this, run 
  $node->attributes->devudo['users']['devudo'] = variable_get('shopmaster_ssh_public_key', '');
  
  // @TODO: Allow tracking of users to grant account

}

/**
 *
 */
function shop_hosting_nodeapi_server_view(&$node){
  
  foreach ($node->attributes as $name => $value) {
    if (is_array($value)){
      foreach($value as $sub_name => $sub_value){
        $node->content['info']['attributes'][$sub_name] = array(
          '#type' => 'item',
          '#title' => "$name:$sub_name",
          '#value' => json_encode($sub_value),
        );  
      }
    } elseif (is_string($value)) {
      $node->content['info']['attributes'] = array(
        '#type' => 'item',
        '#title' => $name,
        '#value' => json_encode($value),
      ); 
    }
    
  }
  
  // SHOW TIP IF PUBLIC KEY IS NOT AVAILABLE
  // Display helpful tips for connecting.
  $pubkey = variable_get('shopmaster_ssh_public_key', '');
  
  // If we don't yet have the server's public key saved as a variable...
  if (empty($pubkey)){
    $output = t("Please save this server's public key to a variable.  On your server, run the following command and then reload this page..");
    $command = 'drush @hostmaster vset shopmaster_ssh_public_key "$(cat ~/.ssh/id_rsa.pub)" --yes';

    $output .= "<div class='command'><input size='160' value='$command' onclick='this.select()' /></div>";
  } else {
    $output = t('Ready');
  }
  
   $node->content['connect'] = array(
    '#type' => 'item',
    '#title' => t('Shopmaster Access'),
    '#description' => $output,
  );
  
}